"""second migration

Revision ID: 3efab5d8ab82
Revises: 34c9da8c0b35
Create Date: 2021-06-16 10:10:01.076520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efab5d8ab82'
down_revision = '34c9da8c0b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.String(length=255), nullable=False))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###
