"""third migration

Revision ID: 4fa4a28404ce
Revises: 3efab5d8ab82
Create Date: 2021-06-16 10:23:39.979701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa4a28404ce'
down_revision = '3efab5d8ab82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
